service: zendesk-customer-app

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'staging'}
  region: us-east-1
  timeout: 30
  environment:
    NODE_ENV: serverless
  deploymentBucket:
    name: zendesk-customer-app-${self:provider.stage}
  vpc:
    securityGroupIds:
      - sg-0ce8610b6007245b5
    subnetIds:
      - subnet-010b5cac0ee0d59e5


functions:
  app:
    handler: index.handler 
    role: arn:aws:iam::675773924938:role/zendesk-customer-app-serverless-execute
    events:
      - http: ANY /
      - http: ANY /{proxy+}
